baseURL: https://perronedotdev.github.io/
languageCode: en-us
title: Perrone.dev
theme: PaperModX
params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  profileMode:
    enabled: true
    title: "Welcome" # optional default will be site title
    subtitle: "Ramblings of a Bearded Man"
    imageUrl: "/images/perronedotdevcircle.png" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Posts
        url: "/posts"
      - name: Tools
        url: "/tools"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: ""

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: Posts
          name: Posts
          url: /posts/
          weight: 10
        - identifier: Tools
          name: Tools
          url: /tools/
          weight: 20
        - identifier: Recipes
          name: Recipes
          url: https://mealie.perrone.dev
          params:
            external: true
          weight: 30
        - identifier: Notes
          name: Notes
          url: https://notes.perrone.dev
          params:
            external: true
          weight: 40
        - identifier: Search
          name: 🔍
          url: /search/
          weight: 50

module:
  imports:
  - path: github.com/hugomods/images

markup:
  goldmark:
    parser:
      attribute:
        block: true
