baseURL: https://perronedotdev.github.io/
languageCode: en-us
title: Perrone.dev
theme: PaperModX
params:
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  profileMode:
    enabled: true
    title: "Welcome" # optional default will be site title
    subtitle: "Ramblings of a Bearded Man"
    imageUrl: "/images/perronedotdevcircle.png" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archives"
      - name: Posts
        url: "/posts"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: Posts
          name: Posts
          url: /posts/
          weight: 10
        - identifier: Recipes
          name: Recipes
          url: https://mealie.perrone.dev
          weight: 20
        - identifier: Notes
          name: Notes
          url: https://notes.perrone.dev
          weight: 30
        - identifier: Search
          name: 🔍
          url: /search/
          weight: 40